// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_c6O_UnarXWA8Q3D_ohR5y6B_N13t8E',
    appId: '1:665321408812:web:8eaaeec367656794150489',
    messagingSenderId: '665321408812',
    projectId: 'timelinesample-11f02',
    authDomain: 'timelinesample-11f02.firebaseapp.com',
    storageBucket: 'timelinesample-11f02.appspot.com',
    measurementId: 'G-4RDJHEDCFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpQRne5dFTFkPuW2xy5lVzNXh_sdUMYlE',
    appId: '1:665321408812:android:438905f81f69a31f150489',
    messagingSenderId: '665321408812',
    projectId: 'timelinesample-11f02',
    storageBucket: 'timelinesample-11f02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdkLo2p0UWki7FRO4LXAI49nG_rMqhwE',
    appId: '1:665321408812:ios:e5095946f52543be150489',
    messagingSenderId: '665321408812',
    projectId: 'timelinesample-11f02',
    storageBucket: 'timelinesample-11f02.appspot.com',
    iosBundleId: 'com.example.flutterTimelines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEdkLo2p0UWki7FRO4LXAI49nG_rMqhwE',
    appId: '1:665321408812:ios:a1e0d40d8d035c5a150489',
    messagingSenderId: '665321408812',
    projectId: 'timelinesample-11f02',
    storageBucket: 'timelinesample-11f02.appspot.com',
    iosBundleId: 'com.example.flutterTimelines.RunnerTests',
  );
}
